### PR TITLE
Maks/imd 7 phone number field

### PR DESCRIPTION
**Pull request by KovalenkoMaks**
## Description
Change Email type from "text" to "email".
Change Phone type from "text" to "tel"

## JIRA ticket
- [IMD-7](https://immortalv.atlassian.net/browse/IMD-7)

[IMD-7]: https://immortalv.atlassian.net/browse/IMD-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by andriiwp3** [comment]
What are these extra commits? Could you please delete them?
I suspect you created your branch from `master` instead of `develop`, which caused this problem

**Comment by andriiwp3** [comment]
Also, as for the name of the PRU, I think it would be better to format it a little differently, e.g.:

> IMD-7: Phone number field

Slthough it's not really very talkative, so I would do this instead:

> IMD-7: Change the type of inputs for phone and email

**Review by andriiwp3 — COMMENTED** [review]
In general, LGTM, the only thing I would ask you to remove unnecessary commits

**Comment by KovalenkoMaks** [comment]
> 

yes, I  create from master. Should I close this PR and make another one from develop branch?

**Comment by andriiwp3** [comment]
I would ask you to try rebasing this branch

**Pull request closed without merging**
